language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload